# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO # ERROR
    tech.jhipster: INFO
    org.hibernate.SQL: ERROR
    com.mycompany.myapp: INFO
    org.springframework.graphql: INFO
    org.springframework.boot.autoconfigure.graphql: INFO
    com.mycompany.myapp.graphql: INFO
    com.mycompany.myapp.service: INFO

spring:
  devtools:
    restart:
      enabled: false
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  graphql:
    path: /graphql
    graphiql:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  datasource:
    enabled: false
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://localhost:1433;database=ProfileProductions;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Led@R@ngDong123!
    hikari:
      poolName: Hikari
      auto-commit: false
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
partner:
  enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://172.168.6.3:1433;database=PanaCIMMC;encrypt=true;trustServerCertificate=true;
    username: itcntt
    password: it-cntt@16
    hikari:
      poolName: Hikari
      auto-commit: false
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
partner2:
  enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://172.168.6.99:1433;database=WMSRAL;encrypt=true;trustServerCertificate=true;
    username: SA
    password: Led@R@ngDong
  hikari:
    poolName: Hikari
    auto-commit: false
    connection-test-query: SELECT 1
    validation-timeout: 5000
    leak-detection-threshold: 60000
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

partner3:
  enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PNM_DB
    username: admin
    password: admin123
    hikari:
      poolName: HikariCP-Partner3
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
      data-source-properties:
        reWriteBatchedInserts: true

  #renderqr:
  #  datasource:
  #    type: com.zaxxer.hikari.HikariDataSource
  #    url: jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=RenderTemQR;encrypt=true;trustServerCertificate=true;
  #    username: renderqr_user
  #    password: StrongPassword123!
  #    hikari:
  #      poolName: Hikari
  #      auto-commit: false
  #      data-source-properties:
  #        cachePrepStmts: true
  #        prepStmtCacheSize: 250
  #        prepStmtCacheSqlLimit: 2048
  #        useServerPrepStmts: true
  jpa:
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    enabled: false
    contexts: dev
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  sleuth:
    # https://github.com/spring-projects/spring-framework/issues/27844#issuescomment-1002866885
    # https://github.com/spring-cloud/spring-cloud-sleuth/issues/2094
    async:
      enabled: false
    enabled: false
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true

server:
  port: 8085

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: "http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200"
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: "https://*.githubpreview.dev"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params"
    allow-credentials: true
    max-age: 1800
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
